from __future__ import annotations

import zipfile
from pathlib import Path

import pandas as pd
from docx import Document
from docx.enum.text import WD_BREAK
from docx.shared import Inches, Pt


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT = PROJECT_ROOT / "manuscript"
TABLES = PROJECT_ROOT / "tables"
FIGURES = PROJECT_ROOT / "figures" / "generated"
SUBMISSION = PROJECT_ROOT / "deliverables" / "preprint"
SUBMISSION.mkdir(exist_ok=True)

AUTHOR = "Tarun Aadithya Magesh Raghavan"
AFFILIATION = "Department of Health Science, McMaster University, Hamilton, Ontario, Canada"
CORRESPONDENCE = (
    "Correspondence: aadithyatarun@gmail.com"
)
FUNDING = "No external funding was received for this project."


TITLE = (
    "A reproducible public-data workflow for spatial and single-cell cardiac "
    "communication analysis"
)
SHORT_TITLE = "Public cardiac communication workflow"


def read_summary_values() -> dict[str, str]:
    summary = pd.read_csv(TABLES / "kuppe_visium_celltype_summary.csv")
    rows = {}
    for zone in ["Control", "Remote zone", "Fibrotic zone", "Infarct zone"]:
        zone_df = summary[summary["zone_label"] == zone].sort_values(
            "dominant_fraction", ascending=False
        )
        top = zone_df.iloc[0]
        rows[zone] = (
            f"{top['cell_type']} dominant spots "
            f"({top['dominant_fraction'] * 100:.1f}%; {int(top['dominant_spots'])}/"
            f"{int(top['n_spots'])})"
        )
    return rows


def manuscript_markdown() -> str:
    top = read_summary_values()
    return f"""# {TITLE}

{AUTHOR}1*

1 {AFFILIATION}

*{CORRESPONDENCE}

Short title: {SHORT_TITLE}

Keywords: human heart; spatial transcriptomics; single-cell RNA-seq; myocardial infarction; heart failure; atrial fibrillation; cell-cell communication; reproducible workflow

## Abstract

Cell-cell communication inference is increasingly used to interpret cardiac single-cell and spatial transcriptomic data, but practical reuse of public human heart datasets is limited by heterogeneous file formats, metadata structures, and disease contexts. We assembled a reproducible public-data workflow for a planned cardiac communication benchmark spanning adult human heart reference data, heart failure, myocardial infarction, atrial fibrillation, and spatial transcriptomics. The workflow downloads public processed files, audits local file contents, records archive members, and generates a first spatial composition analysis from human myocardial infarction Visium data. Four processed Visium AnnData files from the myocardial infarction resource were readable in backed mode and represented 13,106 spatial spots across control, remote-zone, fibrotic-zone, and infarct-zone samples. Dominant spot composition shifted from cardiomyocyte predominance in control myocardium to mixed fibroblast, myeloid, endothelial, cycling-cell, and cardiomyocyte signals in infarct-zone tissue. These outputs establish a transparent starting point for downstream ligand-receptor and pathway-level communication benchmarking while avoiding unsupported claims from methods that have not yet been run.

## Introduction

Cardiac remodeling is a multicellular process involving cardiomyocytes, fibroblasts, endothelial cells, vascular cells, immune cells, adipocytes, neuronal cells, and mesothelial or epicardial populations. Human single-cell and single-nucleus transcriptomic atlases have made it possible to study these populations in healthy and diseased myocardium with increasing resolution. Spatial transcriptomics adds tissue context, which is essential because dissociated single-cell measurements cannot directly preserve the physical organization through which many paracrine and extracellular-matrix-mediated signals operate.

Many computational tools infer cell-cell communication from ligand and receptor expression. These approaches are useful for hypothesis generation, but they differ in ligand-receptor databases, scoring models, treatment of cell abundance, and assumptions about sender and receiver cell types. As a result, cardiac communication results can be sensitive to dataset choice, annotation granularity, preprocessing choices, and whether spatial support is considered. A public, reproducible workflow is therefore needed before making broad claims about robust cardiac signaling programs.

Here, we assembled the first stage of such a workflow. The objective of this preprint is not to claim a completed cross-method communication benchmark. Instead, it provides a reproducible acquisition, audit, and initial spatial-analysis package that can support that benchmark. The analysis emphasizes public human cardiac datasets and reports only results that are generated by the scripts in this repository.

## Results

### Public human cardiac datasets cover complementary disease contexts

The dataset register includes five candidate public resources: an adult human heart reference atlas, a myocardial infarction spatial multi-omic resource, a heart failure single-cell/single-nucleus transcriptomic resource, an atrial fibrillation single-nucleus multiome resource, and an older human cardiac spatial transcriptomics resource. Together, these datasets cover healthy adult heart, myocardial infarction, dilated cardiomyopathy/heart failure, atrial fibrillation, and heart failure etiologies including ischemic, dilated, and hypertrophic cardiomyopathy.

The local audit identified downloaded files in four major classes: processed AnnData spatial files, compressed expression or metadata tables, tar archives of supplementary files, and README metadata. The workflow writes these results to `download_manifest.csv`, `dataset_file_inspection.csv`, and `archive_members.csv`, creating a traceable record of what was available locally at the time of analysis.

### Downloaded resources differ substantially in immediate analysis readiness

The myocardial infarction Visium files were directly readable as `.h5ad` objects, allowing metadata inspection without loading full matrices into memory. In contrast, the heart failure expression file is a very wide compressed count matrix, the atrial fibrillation resource includes sample-specific RNA and ATAC count tables plus a metadata table, and the older cardiac spatial transcriptomics resource is distributed as a small archive of compressed spatial transcriptomics tables. These differences motivate a staged harmonization plan rather than a single parser applied across all datasets.

### Myocardial infarction Visium data provide an immediate spatial anchor

The four processed myocardial infarction Visium files included 4,269 control spots, 2,016 remote-zone spots, 3,175 fibrotic-zone spots, and 3,646 infarct-zone spots. The files contained deconvolved or score-like columns for broad cardiac cell categories including cardiomyocyte, fibroblast, endothelial, myeloid, lymphoid, mast, pericyte, vascular smooth muscle, adipocyte, neuronal, and cycling-cell labels.

Dominant spot composition changed across tissue zones. Control myocardium was overwhelmingly cardiomyocyte-dominant: {top['Control']}. Remote-zone tissue showed a more mixed profile with {top['Remote zone']}. Fibrotic-zone tissue remained cardiomyocyte-dominant by the simple maximum-score rule but showed a large fibroblast component: {top['Fibrotic zone']}. Infarct-zone tissue was no longer cardiomyocyte-dominant; the largest dominant category was {top['Infarct zone']}, followed by substantial myeloid and endothelial components.

### Initial outputs support spatially grounded communication hypotheses

The spatial composition results support a conservative next-stage communication analysis focused on fibroblast, endothelial, myeloid, cycling-cell, and cardiomyocyte axes in myocardial injury. In particular, the infarct-zone shift toward fibroblast, myeloid, and endothelial signals suggests that downstream ligand-receptor analyses should distinguish cell-abundance changes from per-cell expression changes and should prioritize interactions with spatial support. These data do not by themselves prove signaling interactions; they identify tissue zones and cell-type mixtures in which communication inference can be interpreted more carefully.

## Discussion

This work converts a broad cardiac communication benchmark idea into a reproducible public-data workflow with concrete local outputs. The most complete result at this stage is the myocardial infarction Visium spatial composition analysis. It shows the expected transition from cardiomyocyte-dominant control myocardium to mixed infarct-zone tissue enriched for fibroblast, myeloid, endothelial, and cycling-cell signals. This is biologically plausible in the context of injury and remodeling, and it provides a spatial anchor for later communication inference.

The main limitation is that full CellChat, CellPhoneDB, LIANA, NicheNet, and spatial communication analyses have not yet been executed across harmonized single-cell objects. The manuscript therefore avoids claims about cross-method ligand-receptor agreement or robust signaling pathways. Those analyses require additional conversion of the heart failure count matrix, parsing of atrial fibrillation sample-level count tables, recovery or mapping of cell annotations, and construction of comparable sender-receiver cell-type groupings.

The workflow is still useful in its current form because it separates reproducible data acquisition and file auditing from interpretive modeling. This reduces the risk of treating a downloaded accession as analysis-ready when metadata or annotation fields are absent, differently encoded, or not aligned with communication-method requirements. For bioRxiv, the package is best framed as a research resource and reproducible workflow with an initial spatial analysis, rather than as a completed benchmark.

## Materials and Methods

### Dataset selection

Candidate datasets were selected to cover major human cardiac disease and reference contexts relevant to cell-cell communication analysis: healthy adult heart, heart failure/dilated cardiomyopathy, myocardial infarction, atrial fibrillation, and spatial transcriptomics of human cardiac tissue. Inclusion prioritized human cardiac tissue, public access, processed count matrices or AnnData/Seurat-like objects where available, and recoverable cell-type or tissue-zone metadata.

### Data acquisition

Public data were downloaded using `analysis/02_download_public_data.ps1`. Large raw and processed files were stored under `data/raw/`, which is excluded from version control. Downloaded files were summarized by `analysis/03_inspect_downloads.py`, producing a path, file-size, and suffix manifest.

### File inspection

Downloaded `.h5ad` files were read with AnnData in backed mode to avoid unnecessary memory use. Compressed tables were inspected by reading headers and first data rows. Tar archives were inspected without extraction by listing file members, sizes, and suffixes. The inspection outputs were written to `tables/dataset_file_inspection.csv` and `tables/archive_members.csv`.

### Myocardial infarction Visium spatial composition analysis

Processed Visium AnnData files from the myocardial infarction resource were read in backed mode. Broad cell-type score columns were extracted from `.obs`, including adipocyte, cardiomyocyte, endothelial, fibroblast, lymphoid, mast, myeloid, neuronal, pericyte, cycling-cell, and vascular smooth-muscle labels. For each spatial spot, the dominant cell category was defined as the cell-type column with the maximum score. Per-zone summaries included mean score, total score, number of dominant spots, and dominant spot fraction. Results were written to `tables/kuppe_visium_celltype_summary.csv` and `tables/kuppe_visium_spot_summary.csv`.

### Figure generation

Figures were generated from the derived tables using Python, pandas, matplotlib, and seaborn. Figure outputs were written to `figures/generated/` as PNG and PDF files.

### Reproducibility

The repository includes scripts for dataset inventory, download, file inspection, spatial composition summary, and figure generation. The intended from-scratch workflow is documented in `submission/reproducibility_checklist.md`. Large public datasets are not committed to version control and should be regenerated from the download script.

## Data Availability

All data analyzed here are publicly available from the original studies and repositories. Dataset identifiers and source notes are listed in the dataset register and supplementary tables. Processed myocardial infarction spatial transcriptomics data were obtained from the Zenodo record associated with Kuppe et al. Raw and processed local data files are excluded from the repository because of size and redistribution considerations.

## Code Availability

All analysis code required to reproduce the outputs is included with the submission package as a supplementary code archive. The code repository contains scripts for dataset inventory, download, file inspection, spatial composition summary, figure generation, and submission artifact generation.

## Ethics Statement

This study reanalyzes publicly available, de-identified human transcriptomic datasets. No new human participant recruitment, sample collection, intervention, or identifiable human data analysis was performed.

## Funding

{FUNDING}

## Competing Interests

The author declares no competing interests.

## Author Contributions

{AUTHOR}: conceptualization, data curation, formal analysis, software, visualization, writing - original draft, and writing - review and editing.

## Acknowledgements

The author thanks the investigators who generated and shared the public human cardiac transcriptomic datasets reanalyzed here, including the adult human heart atlas, myocardial infarction spatial multi-omics, human heart failure single-cell transcriptomics, atrial fibrillation multiome, and human cardiac spatial transcriptomics resources. The author also acknowledges the open-source scientific Python ecosystem used for data inspection, analysis, visualization, and manuscript preparation. OpenAI ChatGPT/Codex was used to assist with workflow organization, code generation, reproducible analysis execution, and manuscript drafting under author direction and review.

## References

1. Litvinukova M, Talavera-Lopez C, Maatz H, et al. Cells of the adult human heart. Nature. 2020;588:466-472. doi:10.1038/s41586-020-2797-4

2. Kuppe C, Ramirez Flores RO, Li Z, et al. Spatial multi-omic map of human myocardial infarction. Nature. 2022;608:766-777. doi:10.1038/s41586-022-05060-x

3. Koenig AL, Shchukina I, Amrute J, et al. Single-cell transcriptomics reveals cell-type-specific diversification in human heart failure. Nature Cardiovascular Research. 2022;1:263-280. doi:10.1038/s44161-022-00028-6

4. Leblanc FJA, Yiu CHK, Moreira LM, et al. Single-nucleus multi-omics implicates androgen receptor signaling in cardiomyocytes and NR4A1 regulation in fibroblasts during atrial fibrillation. Nature Cardiovascular Research. 2025;4:433-444. doi:10.1038/s44161-025-00626-0

5. Gidlöf O, Smith G. Spatial Transcriptomics of Human Cardiac Tissue. GEO accession GSE135805. Public 2019.

## Figure Legends

Figure 1. Dataset register and local data audit. Candidate public human cardiac datasets span healthy adult heart, myocardial infarction, heart failure, atrial fibrillation, and spatial transcriptomics resources. The local file audit records downloaded file classes used by the reproducible workflow.

Figure 2. Human myocardial infarction Visium cell-type composition. Left, fraction of spots for which each broad cardiac cell type had the maximum score. Right, mean cell-type score by tissue zone. Control myocardium is cardiomyocyte-dominant, whereas infarct-zone tissue shows increased fibroblast, myeloid, endothelial, and cycling-cell components.

## Tables

Table 1. Candidate public datasets included in the dataset register.

Table 2. Local downloaded file audit.

Table 3. Myocardial infarction Visium cell-type summary.
"""


def add_md_to_doc(doc: Document, md: str) -> None:
    for raw_line in md.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("# "):
            doc.add_heading(line[2:], level=0)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=1)
        elif line.startswith("### "):
            doc.add_heading(line[4:], level=2)
        elif line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
        else:
            doc.add_paragraph(line)


def build_docx(md: str) -> None:
    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)
    styles = doc.styles
    styles["Normal"].font.name = "Arial"
    styles["Normal"].font.size = Pt(10.5)
    styles["Normal"].paragraph_format.space_after = Pt(6)
    add_md_to_doc(doc, md)

    doc.add_paragraph().add_run().add_break(WD_BREAK.PAGE)
    doc.add_heading("Figures", level=1)
    for figure, caption in [
        (
            FIGURES / "dataset_overview.png",
            "Figure 1. Dataset register and local data audit.",
        ),
        (
            FIGURES / "kuppe_visium_celltype_overview.png",
            "Figure 2. Human myocardial infarction Visium cell-type composition.",
        ),
    ]:
        if figure.exists():
            doc.add_picture(str(figure), width=Inches(6.5))
            doc.add_paragraph(caption)

    out = SUBMISSION / "preprint_manuscript.docx"
    doc.save(out)
    print(f"Wrote {out}")


def build_supplementary_workbook() -> None:
    out = SUBMISSION / "supplementary_tables.xlsx"
    with pd.ExcelWriter(out, engine="openpyxl") as writer:
        sheets = {
            "dataset_register": PROJECT_ROOT / "data" / "dataset_inventory_review.csv",
            "download_manifest": TABLES / "download_manifest.csv",
            "file_inspection": TABLES / "dataset_file_inspection.csv",
            "archive_members": TABLES / "archive_members.csv",
            "visium_celltype_summary": TABLES / "kuppe_visium_celltype_summary.csv",
        }
        for sheet, path in sheets.items():
            pd.read_csv(path).to_excel(writer, sheet_name=sheet[:31], index=False)
    print(f"Wrote {out}")


def write_submission_files(md: str) -> None:
    (SUBMISSION / "preprint_manuscript.md").write_text(md, encoding="utf-8")
    (SUBMISSION / "preprint_cover_note.txt").write_text(
        f"""Dear bioRxiv Screening Team,

Please consider this manuscript for posting in bioRxiv, preferably under Bioinformatics or Systems Biology.

The manuscript reports a reproducible public-data workflow and initial spatial transcriptomics reanalysis of human cardiac datasets. It uses only public, de-identified datasets and does not report new clinical recruitment, intervention, diagnostic claims, or therapeutic recommendations.

Author:
{AUTHOR}
{AFFILIATION}
{CORRESPONDENCE}

Sincerely,
{AUTHOR}
""",
        encoding="utf-8",
    )
    (SUBMISSION / "preprint_metadata.md").write_text(
        f"""# Preprint Metadata

Title: {TITLE}

Category: Bioinformatics

Secondary category: Systems Biology

Author: {AUTHOR}

Affiliation: {AFFILIATION}

{CORRESPONDENCE}

Abstract: see manuscript.

Competing interests: The author declares no competing interests.

Funding: {FUNDING}

Ethics: This study reanalyzes publicly available, de-identified human transcriptomic datasets. No new human participant recruitment, sample collection, intervention, or identifiable human data analysis was performed.

Data availability: All data are publicly available from original repositories and accessions listed in the manuscript and supplementary tables.

Code availability: All code is included in the supplementary code archive supplied with this submission package.

Preferred license: CC BY 4.0.
""",
        encoding="utf-8",
    )
    (SUBMISSION / "reproducibility_checklist.md").write_text(
        """# Reproducibility Checklist

Run from the project root:

```powershell
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\01_dataset_inventory.py
powershell.exe -ExecutionPolicy Bypass -File analysis\\02_download_public_data.ps1
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\03_inspect_downloads.py
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\04_inspect_dataset_contents.py
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\05_summarize_kuppe_visium.py
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\06_make_initial_spatial_figures.py
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\07_make_dataset_overview_figure.py
& 'C:\\Users\\mages\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe' analysis\\08_build_biorxiv_submission.py
```

Before upload:

- Confirm that the bioRxiv account email is correct in the submission system.
- Upload `preprint_manuscript.docx`.
- Upload `supplementary_tables.xlsx`.
- Upload `supplementary_code.zip`.
- Upload separate figure files if requested by the submission system.
- Select CC BY 4.0 as the reuse license unless a different license is intentionally preferred.
""",
        encoding="utf-8",
    )
    print(f"Wrote text submission files in {SUBMISSION}")


def build_code_archive() -> None:
    out = SUBMISSION / "supplementary_code.zip"
    include_dirs = ["analysis", "data", "figures", "manuscript", "references", "tables"]
    excluded_parts = {
        ".git",
        ".cache",
        "__pycache__",
        "raw",
        "processed",
        "external",
        "generated",
        "submission",
    }
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for directory in include_dirs:
            root = PROJECT_ROOT / directory
            if not root.exists():
                continue
            for path in root.rglob("*"):
                if not path.is_file():
                    continue
                rel = path.relative_to(PROJECT_ROOT)
                if any(part in excluded_parts for part in rel.parts):
                    continue
                archive.write(path, rel.as_posix())
        for path in [
            PROJECT_ROOT / "README.md",
            PROJECT_ROOT / ".gitignore",
            PROJECT_ROOT / "requirements.txt",
            PROJECT_ROOT / "LICENSE",
            PROJECT_ROOT / "CITATION.cff",
        ]:
            if path.exists():
                archive.write(path, path.name)
    print(f"Wrote {out}")


def main() -> None:
    md = manuscript_markdown()
    write_submission_files(md)
    build_docx(md)
    build_supplementary_workbook()
    build_code_archive()


if __name__ == "__main__":
    main()
